project:
  type: website
  output-dir: docs

website:
  title: "Grazing Intensity VRE (Virtual Research Environment)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: create_db.qmd
        text: Create DB
      - href: colect_data.qmd
        text: Colecta de datos
      - href: logs.qmd
        text: Logs
      - icon: github
        href: https://github.com/serpam/sumhal_vreGI
        aria-label: GitHub repo 
      - icon: twitter
        href: https://twitter.com/SERPAM_EEZ
        aria-label: SERPAM Twitter

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true