project:
  type: website
  output-dir: docs

website:
  title: "Grazing Intensity VRE (Virtual Research Environment)"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:colectadatos
      - sidebar:apps
      - icon: github
        href: https://github.com/serpam/sumhal_vreGI
        aria-label: GitHub repo 
      - icon: twitter
        href: https://twitter.com/SERPAM_EEZ
        aria-label: SERPAM Twitter
        
  sidebar:
    - id: colectadatos
      title: "Colecta Datos"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - href: create_db.qmd
          text: Create DB
        - href: colect_data.qmd
          text: Colecta de datos
        - href: logs.qmd
          text: Logs
    - id: apps
      title: "Apps"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - href: https://github.com/serpam/convertGPS_cattle
          text: Converter apps
  
  
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true